services:
  zookeeper:
    image: bitnami/zookeeper:3.9
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - cdr-network
    healthcheck:
      test: ["CMD", "echo", "ruok", "|", "nc", "-w", "2", "localhost", "2181"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 512m
        reservations:
          memory: 256m

  kafka:
    image: bitnami/kafka:3.8
    ports:
      - "9093:9093"
      - "9092:9092"
    environment:
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      zookeeper:
        condition: service_healthy
    networks:
      - cdr-network
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 1024m
        reservations:
          memory: 512m

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=<your-pass>
      - MYSQL_DATABASE=cdr_db
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p<your-pass>"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 60s
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - cdr-network
    deploy:
      resources:
        limits:
          memory: 512m
        reservations:
          memory: 256m

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=<your-pass>
      - POSTGRES_DB=cdr2_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - cdr-network
    deploy:
      resources:
        limits:
          memory: 512m
        reservations:
          memory: 256m

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    container_name: keycloak
    ports:
#      - "8081:8080"
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=<your-pass>
      - KC_HTTP_PORT=8080
      - KC_HOSTNAME_PORT=8080
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME_STRICT=false
      - KC_PROXY=edge
      - KC_FRONTEND_URL=http://keycloak:8080
      - KC_HOSTNAME=keycloak
    command:
      - start-dev
      - --import-realm
      - --hostname-strict=false


    healthcheck:
      test: [ "CMD", "sh", "-c", "cat /proc/net/tcp | grep 1F90" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    networks:
      - cdr-network

  backend:
    build:
      context: ./ms-backend
    ports:
      - "8084:8080"
    depends_on:
      keycloak:
        condition: service_healthy
      mysql:
        condition: service_healthy
      kafka:
        condition: service_healthy
      zookeeper:
        condition: service_healthy
    networks:
      - cdr-network
    deploy:
      resources:
        limits:
          memory: 1024m
        reservations:
          memory: 512m

  loader:
    build:
      context: ./ms-loader
    ports:
      - "8082:8080"
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/cdr2_db
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - LOADER_DIRECTORY_PATH=/input
    volumes:
      - ./ms-loader/src/main/resources/input:/input
    networks:
      - cdr-network
    deploy:
      resources:
        limits:
          memory: 512m
        reservations:
          memory: 256m

  frontend:
    build:
      context: ./ms-frontend
    ports:
      - "8083:80"
    depends_on:
      - backend
    networks:
      - cdr-network
    deploy:
      resources:
        limits:
          memory: 256m
        reservations:
          memory: 128m

networks:
  cdr-network:
    driver: bridge

volumes:
  keycloak_data:
