version: '3.8'
services:
  kafka:
    image: bitnami/kafka:3.8
    ports:
      - "9093:9093"
    environment:
    - KAFKA_CFG_BROKER_ID=1
    - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
    - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,EXTERNAL://:9093
    - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9093
    - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:3.9
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-habiba@2005}
      MYSQL_DATABASE: cdr_db
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD:-habiba@2005}" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: habiba@2005
      POSTGRES_DB: cdr2_db
    ports:
      - '5432:5432'

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    container_name: keycloak
    ports:
      - "8081:8080"
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
    command: start-dev
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/realms/cdr-realm/.well-known/openid-configuration" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 60s

  backend:
    build:
      context: ./ms-backend
    ports:
      - "8080:8080"
    depends_on:
      - keycloak
      - mysql
      - kafka
      - zookeeper

  loader:
      build:
        context: ./ms-loader
      ports:
        - '8082:8080'
      depends_on:
        - postgres
        - kafka
      environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/cdr2_db
        - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
        - LOADER_DIRECTORY_PATH=/input
      volumes:
        - C:\IntelliJ IDEA 2024.2.4\Call_Detail_Record_Platform\ms-loader\src\main\resources\input:/input

  frontend:
    build: ./ms-frontend
    ports:
      - "8083:80"
    depends_on:
      - backend