spring:
  application:
    name: ms-loader

  datasource:
    url: jdbc:postgresql://postgres:5432/cdr2_db
    username: postgres
    password: <your-pass>
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 3
      properties:
        max.block.ms: 30000
        delivery.timeout.ms: 30000

loader:
  directory:
    path: /input
  schedule:
    rate: 60000

kafka:
  topic: cdr-records

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        transaction: DEBUG
