apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-backend
  template:
    metadata:
      labels:
        app: ms-backend
    spec:
      containers:
        - name: ms-backend
          image: call_detail_record_platform-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ms-backend-service
spec:
  type: NodePort
  selector:
    app: ms-backend
  ports:
    - nodePort: 30084
      port: 8084
      targetPort: 8080
