apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ms-frontend
  template:
    metadata:
      labels:
        app: ms-frontend
    spec:
      containers:
        - name: ms-frontend
          image: call_detail_record_platform-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ms-frontend-service
spec:
  type: NodePort
  selector:
    app: ms-frontend
  ports:
    - nodePort: 30083
      port: 8083
      targetPort: 80
